export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-zinc-300 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
        <p className="text-sm text-zinc-500 mb-8">Last updated: January 30, 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Postmagiq ("Service"), you agree to be bound by these Terms
              of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Postmagiq is an AI-powered content creation platform that helps users generate
              social media content and publish it to connected social media accounts including
              LinkedIn, X (Twitter), and Threads.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Account Registration</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You must provide accurate and complete information when creating an account</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must be at least 18 years old to use this Service</li>
              <li>One person or entity may not maintain more than one account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generate or publish content that is illegal, harmful, or violates others' rights</li>
              <li>Create spam, misleading content, or engage in deceptive practices</li>
              <li>Impersonate others or misrepresent your affiliation</li>
              <li>Violate the terms of service of connected social media platforms</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use the Service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Content Ownership</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Your Content:</strong> You retain ownership of content you create using the Service</li>
              <li><strong>License to Us:</strong> You grant us a license to process your content to provide the Service</li>
              <li><strong>AI-Generated Content:</strong> Content generated by our AI tools is owned by you</li>
              <li><strong>Responsibility:</strong> You are responsible for content you publish to social media</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Social Media Integration</h2>
            <p className="mb-3">When you connect social media accounts:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You authorize us to publish content on your behalf when you click "Publish"</li>
              <li>You are responsible for ensuring content complies with each platform's policies</li>
              <li>You can disconnect accounts at any time through Settings</li>
              <li>We are not responsible for actions taken by social media platforms on your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Subscription and Payments</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Some features require a paid subscription</li>
              <li>Subscriptions are billed monthly or yearly as selected</li>
              <li>You can cancel your subscription at any time</li>
              <li>Refunds are handled on a case-by-case basis</li>
              <li>We reserve the right to change pricing with notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Service Availability</h2>
            <p>
              We strive to provide reliable service but do not guarantee 100% uptime.
              We may modify, suspend, or discontinue features with reasonable notice.
              We are not liable for any downtime or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Postmagiq shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages resulting from
              your use of the Service. Our total liability shall not exceed the amount you paid
              us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" without warranties of any kind, either express
              or implied. We do not warrant that the Service will be uninterrupted, error-free,
              or that AI-generated content will be accurate or suitable for any purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these terms.
              You may delete your account at any time. Upon termination, your right to use the
              Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of
              material changes via email or through the Service. Continued use after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">13. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable law,
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">14. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{' '}
              <a href="mailto:support@postmagiq.com" className="text-purple-400 hover:text-purple-300">
                support@postmagiq.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
